/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/tree-4/model.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['??????????_1']: THREE.Mesh
    ['??????????_1_1']: THREE.Mesh
  }
  materials: {
    ['??????']: THREE.MeshStandardMaterial
    ['???????_??????']: THREE.MeshStandardMaterial
  }
}

export function TreeFour(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/tree-4/model.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['??????????_1'].geometry} material={materials['??????']} />
      <mesh geometry={nodes['??????????_1_1'].geometry} material={materials['???????_??????']} />
    </group>
  )
}

useGLTF.preload('/models/tree-4/model.glb')
