/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/house/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function House(props: any) {
  const { nodes, materials } = useGLTF('/models/house/model.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Sawmill_1.geometry} material={materials.RoofTiles_Red} />
        <mesh geometry={nodes.Sawmill_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Sawmill_3.geometry} material={materials.Wood_Side} />
        <mesh geometry={nodes.Sawmill_4.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Sawmill_5.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Sawmill_6.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Sawmill_7.geometry} material={materials.Wood_Light} />
        <mesh geometry={nodes.Sawmill_8.geometry} material={materials.Stone_Dark} />
        <mesh geometry={nodes.Sawmill_9.geometry} material={materials.Plaster} />
        <mesh geometry={nodes.Sawmill_10.geometry} material={materials.Stone_Light} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/house/model.glb')
