/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/island/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Iseland(props: any) {
  const { nodes, materials } = useGLTF('/models/iseland/model.glb')
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1907009853.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1833200623.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group767309464.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1047130556.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group34140756.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group599290752.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1890178627.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group324817132.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1180255365.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1830346522.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group986161850.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group734284808.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group858885018.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1861304507.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group150474535.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1029689905.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1678092117.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1340148613.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group3007029.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group396515554.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group620404869.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1142921997.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group783008413.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group475868568.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group771098136.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1661560633.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1288567976.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group2134765421.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1922369548.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group107018821.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1814464028.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group654750372.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group561706230.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1733637446.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1754519681.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1168828220.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group889118584.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group271323194.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1992776559.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1794726675.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1444963344.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group447429556.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group302771954.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1356912078.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1622419645.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1242346347.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group423171390.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1889879536.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group597624186.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group737069192.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1174736347.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group512670081.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group145650752.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1165663780.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group615202046.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group665117847.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group2141883061.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1956408514.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1573632195.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group191349948.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1489245576.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group624080166.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group547813215.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group443772894.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1634341855.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1981546557.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group676907512.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group415510944.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1597509149.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1158573957.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1782538837.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group438538056.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group716347833.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group2127422963.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group655986766.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1303039147.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group116158582.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1101735918.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group133283747.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1033721589.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1084787493.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group937971834.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group438297063.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1715968370.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group588801848.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1686734317.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1581313461.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1494306542.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group935358248.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1764158909.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1739569285.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1905712674.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group41106183.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group832184551.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group239378099.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group998526784.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group789584188.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1421929652.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group894192591.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group614088269.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1556665224.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group624957455.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group734299636.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh2009401224.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh2009401224_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh843366372.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh843366372_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh1146194953.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1146194953_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh506122935.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh506122935_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1573540807.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1573540807_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh266667135.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh266667135_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1045676722.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1045676722_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh313951583.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh313951583_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh2035836735.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh2035836735_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh403363102.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh403363102_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh112527887.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh112527887_1.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh205929623.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh205929623_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1414888727.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh1414888727_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh2124609110.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh2124609110_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh86228150.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh86228150_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1672718913.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1672718913_1.geometry} material={materials.mat18} />
    </group>
  )
}

useGLTF.preload('/models/iseland/model.glb')
