/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/land/model.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Island01_Cylinder-Mesh']: THREE.Mesh
    ['Island01_Cylinder-Mesh_1']: THREE.Mesh
  }
  materials: {
    Dirt: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
  }
}

export function Land(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/land/model.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Island01_Cylinder-Mesh'].geometry} material={materials.Dirt} />
      <mesh geometry={nodes['Island01_Cylinder-Mesh_1'].geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload('/models/land/model.glb')
