/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/octopus/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Octopus(props: any) {
  const { nodes, materials } = useGLTF('/models/octopus/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Octopus_mesh.geometry} material={materials.lambert2SG} castShadow />
    </group>
  )
}

useGLTF.preload('/models/octopus/model.glb')
