/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/soil/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Soil(props: any) {
  const { nodes, materials } = useGLTF('/models/soil/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.mat18} />
    </group>
  )
}

useGLTF.preload('/models/soil/model.glb')
