/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/models/tree-1/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TreeOne(props:any) {
  const { nodes, materials } = useGLTF('/models/tree-1/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat9} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat20} />
    </group>
  )
}

useGLTF.preload('/models/tree-1/model.glb')
